services:
  fruitnanny:
    build:
      context: .
      dockerfile: docker/fruitnanny/Dockerfile
    restart: always
    privileged: true
    volumes:
      - ./fruitnanny_config.js:/opt/fruitnanny/fruitnanny_config.js
      - ./bin:/opt/fruitnanny/bin
      - ./views:/opt/fruitnanny/views
      - ./public:/opt/fruitnanny/public
      - ./server:/opt/fruitnanny/server
    network_mode: "host"
    expose:
      - 7000

  nginx:
    image: arm32v6/nginx:alpine
    restart: always
    network_mode: "host"
    depends_on:
      - fruitnanny
    volumes:
      - ./configuration/nginx/fruitnanny_http:/etc/nginx/conf.d/default.conf
      - ./configuration/nginx/fruitnanny_https:/etc/nginx/conf.d/default-ssl.conf
      - ./configuration/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./configuration/ssl:/etc/fruitnanny-ssl
      - ./hls:/hls
    ports:
      - "80:80"
      - "443:443"
