services:
  gstreamer-video:
    build:
      context: .
      dockerfile: docker/gstreamer/Dockerfile
    image: fruitnanny-gstreamer
    restart: always
    privileged: true
    network_mode: "host"
    command:
      - sh
      - -c
      - >-
        rpicam-vid --awbgains 1.0,1.0  --nopreview --inline -t 0
        --width 1920 --height 1080 --framerate 30 --intra 8 --hflip --vflip -o - |
        gst-launch-1.0 -v fdsrc !
        h264parse config-interval=-1 !
        hlssink2 max-files=10 target-duration=1
        location=/hls/segment%05d.ts
        playlist-location=/hls/stream.m3u8
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /sys:/sys
      - /run/udev:/run/udev:ro
      - ./hls:/hls

  gstreamer-audio:
    image: fruitnanny-gstreamer
    restart: always
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    command: >
      gst-launch-1.0 -v alsasrc device=hw:1 !
      audioconvert ! audioresample !
      lamemp3enc ! mpegaudioparse !
      hlssink2 max-files=10 target-duration=1
      location=/hls/audio-segment%05d.ts
      playlist-location=/hls/audio.m3u8
    volumes:
      - ./hls:/hls

  fruitnanny:
    build:
      context: .
      dockerfile: docker/fruitnanny/Dockerfile
    restart: always
    privileged: true
    volumes:
      - ./fruitnanny_config.js:/opt/fruitnanny/fruitnanny_config.js
      - ./bin:/opt/fruitnanny/bin
      - ./views:/opt/fruitnanny/views
      - ./public:/opt/fruitnanny/public
      - ./server:/opt/fruitnanny/server
    network_mode: "host"
    expose:
      - 7000

  nginx:
    image: arm32v6/nginx:alpine
    restart: always
    network_mode: "host"
    depends_on:
      - fruitnanny
    volumes:
      - ./configuration/nginx/fruitnanny_http:/etc/nginx/conf.d/default.conf
      - ./configuration/nginx/fruitnanny_https:/etc/nginx/conf.d/default-ssl.conf
      - ./configuration/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./configuration/ssl:/etc/fruitnanny-ssl
      - ./hls:/hls
    ports:
      - "80:80"
      - "443:443"
